version: '2.2'
services:
  jupyter:
    image: jupyter/datascience-notebook
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 8888:8888
    # エラル
    # Invalid response: 403 Forbidden
    # Cannot read property 'path' of undefined 
    # volumes:
    #   - ./jupyterlab:/home/jovyan/work
    working_dir: /home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
    restart: always